import type { AppProps } from "next/app";
import Head from "next/head";
import { Fragment } from "react";
import BasicLayout from "../styles/theme";
import type { Page } from "../types/page";

// this should give a better typing
type Props = AppProps & {
  Component: Page;
};
const MyApp = ({ Component, pageProps }: Props) => {
  // adjust accordingly if you disabled a layout rendering option
  const getLayout = Component.getLayout ?? ((page) => page);
  const Layout = Component.layout ?? Fragment;

  return (
    <Layout>
      <BasicLayout>
        <Head>
          <title>Porto-RifqiF</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Navbar</h1>
        {getLayout(<Component {...pageProps} />)}
        <h2>Footer</h2>
      </BasicLayout>
    </Layout>
  );

  // or swap the layout rendering priority
  // return getLayout(<Layout><Component {...pageProps} /></Layout>)
};

export default MyApp;
